name: 'Issue States'

on:
  project_card:
    types: [created, edited, moved]

permissions:
  repository-projects: read
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/issue-states@v2
        with:
          github-token: ${{ github.token }}
          open-issue-columns: 'Reviewer approved, Needs Review, In progress, Ready to Play, Ready to Estimate'
          closed-issue-columns: 'Done'
          log-output: false